Description: CloudFormation install wordpress
Parameters: 
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair
  DBName:
    Default: wordpressdb
    Description: The WordPress databse name
    Type: String 
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric 
  DBUser:
    NoEcho: 'true'
    Description: The WordPress database admin account username
    Type: String 
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters
  DBPassword: 
    NoEcho: 'true'
    Description: The wordpress database admin account username
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'  
    ConstraintDescription: must contain only alphanumeric characters.



Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable tcp access on ports 80 and 22"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 184.185.72.92/32
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 184.185.72.92/32
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: "Name"
          Value: "TestCloudFormation"
        - Key: "Owner"
          Value: "chen.xu"
        - Key: "ExpirationDate"
          Value: "2019-06-18"
        - Key: "Project"
          Value: "training"
        - Key: "Environment"
          Value: "Development"
      ImageId: ami-0cc96feef8c6bbff3
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: WebSecurityGroup
####################################################################
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              sudo yum update -y aws-cfn-bootstrap
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         -- resource WebServer '
            - '         --configsets wordpress_install '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+

            - '/opt/aws/bin/cfn-signal -e $? '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource WebServer '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+
####################################################################
